### ISSUE TITLE
Please fix terrain example!

### ISSUE THREAD

**Issue by Thundros** [rogerscg/era-engine#12]
Hi @rogerscg ! Would be great if you could fix the terrain example & put it in the demos so I & other people can test it out!

Thanks a bunch, brother! <3

**Comment by Thundros** [comment]
@rogerscg : Hello?

**Comment by rogerscg** [comment]
Hey @Thundros , found a bit of time to work on the engine. I'm hoping to get to a terrain example soon. The way the engine is used/built is a bit different now.

**Comment by Thundros** [comment]
@rogerscg : I would be honored to beta test it! <3 When are you going to have a terrain example?

MUCH thanks brother! <3

**Comment by rogerscg** [comment]
Hi @Thundros , I recently fixed the terrain example. It's a free-roam entity with a terrain map. It takes a bit to load since I'm also generating terrain textures on the client. Take a look when you get the chance.
