### ISSUE TITLE
PLEASE make this run at 60 FPS!!!

### ISSUE THREAD

**Issue by Thundros** [rogerscg/era-engine#2]
Hello! :) First off, I'd like to say 'WOW! KEEP UP THE GREAT WORK!' This Character example is EXACTLY what I've been looking for! Secondly, I'm only getting 40 - 45 FPS on an NVidia GeForce GTX 960M graphics card & would like to see it run at 60 FPS at all possible!

Once again, KEEP UP THE GREAT WORK & finally have a good day!

**Comment by Thundros** [comment]
@rogerscg

**Comment by rogerscg** [comment]
Hey @Thundros, sorry, didn't even check my notifications! Still new to running a public repo. Is your FPS in the renderer stats box showing 40-45? If so, that's definitely not good.

**Comment by Thundros** [comment]
@rogerscg : Yes. Can you PLEASE fix it?!

**Comment by rogerscg** [comment]
I will look into it when I get the chance. Are any of the other examples giving you poor performance? Or just the character one?

**Comment by Thundros** [comment]
@rogerscg : Really?! That would be GREAT! I am willing to Beta test for you if that is what it takes to fix this! I REALLY need this! Thank you! <3 Will get back to you on other examples!

**Comment by Thundros** [comment]
@rogerscg : Yes. ALL the demos are getting up to 45.

**Comment by rogerscg** [comment]
If you go to chrome://settings/system, do you have hardware acceleration enabled?

**Comment by Thundros** [comment]
@rogerscg : yes, but I shouldn't need it.

**Comment by rogerscg** [comment]
Okay, thanks for checking. It's also possible you're running on integrated graphics. Make sure Chrome is using your AMD card.

**Comment by rogerscg** [comment]
Also, do you have any tabs/programs running in the background?

**Comment by Thundros** [comment]
@rogerscg : I have an NVidia GeForce GTX 960M.

And no.

**Comment by Thundros** [comment]
@rogerscg : hello?

**Comment by rogerscg** [comment]
Just remember that I work on this for fun, so I won't be able to address issues immediately.

Does this demo for you run at 60FPS?
https://threejs.org/examples/#webgl_lights_physical

**Comment by Thundros** [comment]
@rogerscg : Yes

**Comment by rogerscg** [comment]
Hi @Thundros , I recently added `high-performance` to the WebGL Renderer. I also added a settings panel for you to try and diagnose your issues. Mind giving it a shot?

**Comment by Thundros** [comment]
@rogerscg : sorry for the late reply. I have been busy working on my project. Anyway, sure I can give it a try. Will let you know! Thanks! :)

**Comment by Thundros** [comment]
@rogerscg : Sorry for the late reply. As always, been working on my project. But I checked out all the demos again, & for some reason the FPS issue is gone. All of them run @ 60 FPS. Can you please add a Terrain-slope-angle example?
