### ISSUE TITLE
Character example: defaultEraRenderer is not defined.

### ISSUE THREAD

**Issue by shootTheLuck** [rogerscg/era-engine#6]

**Comment by shootTheLuck** [comment]
Sorry!  I meant to say the imports in the top of the file ... examples/character/index.js.  Cheers!

**Comment by rogerscg** [comment]
Hi @shootTheLuck , sorry it took so long for me to respond. I will fix that right now :) The engine isn't quite stable, but hopefully you can still make use of it!

**Comment by rogerscg** [comment]
Just fixed the character example. If you can reproduce the issue with audio, please file another issue!
